
INSERT INTO preguntas (titulo, respuesta_correcta, respuesta_A, respuesta_B, respuesta_C, respuesta_D, categoria_id, autor_id, validada_por, dificultad_id, validada) VALUES

# CAT 1 HISTORIA - FÁCIL (15)
questions.append(("¿En qué país se originó el fútbol moderno?", "A", "Inglaterra", "Francia", "Alemania", "Italia", 1, 1, 1, 1, true))
questions.append(("¿En qué año se fundó la FIFA?", "B", "1896", "1904", "1912", "1920", 1, 1, 1, 1, true))
questions.append(("¿Quién es conocido como el Rey del Fútbol?", "A", "Pelé", "Maradona", "Cruyff", "Di Stéfano", 1, 1, 1, 1, true))
questions.append(("¿Qué país ganó el primer Mundial de fútbol en 1930?", "C", "Argentina", "Brasil", "Uruguay", "Yugoslavia", 1, 1, 1, 1, true))
questions.append(("¿En qué año se celebró el primer Mundial de fútbol?", "A", "1930", "1934", "1926", "1928", 1, 1, 1, 1, true))
questions.append(("¿Cuántos goles marcó Pelé a lo largo de su carrera oficial?", "B", "1000", "1281", "950", "1100", 1, 1, 1, 1, true))
questions.append(("¿Qué club es conocido como el equipo del siglo XX según la FIFA?", "A", "Real Madrid", "Barcelona", "Manchester United", "Bayern Munich", 1, 1, 1, 1, true))
questions.append(("¿Con qué selección debutó Pelé en un Mundial?", "A", "Brasil", "Argentina", "Uruguay", "Colombia", 1, 1, 1, 1, true))
questions.append(("¿Quién fue el máximo goleador del Mundial de 1958?", "B", "Pelé", "Fontaine", "Garrincha", "Di Stéfano", 1, 1, 1, 1, true))
questions.append(("¿En qué año se jugó el primer partido internacional de fútbol?", "B", "1870", "1872", "1875", "1880", 1, 1, 1, 1, true))
questions.append(("¿Qué selección ganó el Mundial de 1966?", "C", "Alemania", "Portugal", "Inglaterra", "Argentina", 1, 1, 1, 1, true))
questions.append(("¿Qué jugador fue apodado La Pulga?", "D", "Pelé", "Cruyff", "Maradona", "Messi", 1, 1, 1, 1, true))
questions.append(("¿En qué año nació Pelé?", "B", "1938", "1940", "1943", "1945", 1, 1, 1, 1, true))
questions.append(("¿Qué país organizó el Mundial de 1966?", "A", "Inglaterra", "Alemania", "Italia", "España", 1, 1, 1, 1, true))
questions.append(("¿Cuántos mundiales ganó Brasil en total hasta 2022?", "C", "4", "3", "5", "6", 1, 1, 1, 1, true))

# CAT 1 HISTORIA - MEDIA (15)
questions.append(("¿Quién marcó el Gol del Siglo en el Mundial de 1986?", "B", "Pelé", "Maradona", "Zidane", "Ronaldo", 1, 1, 1, 2, true))
questions.append(("¿En qué año se creó la UEFA?", "C", "1950", "1952", "1954", "1956", 1, 1, 1, 2, true))
questions.append(("¿Qué jugador ganó el primer Balón de Oro de la historia en 1956?", "A", "Stanley Matthews", "Di Stéfano", "Puskas", "Kopa", 1, 1, 1, 2, true))
questions.append(("¿En qué Mundial marcó Pelé su primer gol con Brasil?", "B", "1954", "1958", "1962", "1966", 1, 1, 1, 2, true))
questions.append(("¿Qué selección fue subcampeona del mundo en 1930?", "D", "Brasil", "Chile", "EE.UU.", "Argentina", 1, 1, 1, 2, true))
questions.append(("¿Quién entrenó a Brasil en el Mundial de 1970?", "A", "Zagallo", "Feola", "Saldanha", "Parreira", 1, 1, 1, 2, true))
questions.append(("¿En qué año se inauguró el estadio de Wembley original?", "B", "1920", "1923", "1927", "1930", 1, 1, 1, 2, true))
questions.append(("¿Qué jugador marcó hat-trick en la final del Mundial de 1966?", "B", "Charlton", "Hurst", "Peters", "Moore", 1, 1, 1, 2, true))
questions.append(("¿Quién fue el primer jugador africano en ganar el Balón de Oro?", "B", "Drogba", "Weah", "Eto'o", "Mané", 1, 1, 1, 2, true))
questions.append(("¿En qué país se disputó la final del Mundial de 1954?", "B", "Francia", "Suiza", "Alemania", "Austria", 1, 1, 1, 2, true))
questions.append(("¿Qué jugador fue conocido como La Saeta Rubia?", "D", "Pelé", "Cruyff", "Puskas", "Di Stéfano", 1, 1, 1, 2, true))
questions.append(("¿Cuántos goles marcó Just Fontaine en el Mundial de 1958, récord hasta hoy?", "A", "13", "11", "10", "12", 1, 1, 1, 2, true))
questions.append(("¿Qué apodo tenía la gran selección húngara de los años 50?", "B", "Los Mágicos", "Los Magiares Mágicos", "La Máquina Roja", "El Equipo Dorado", 1, 1, 1, 2, true))
questions.append(("¿En qué año se disputó la primera Copa de Europa de clubes?", "C", "1953", "1954", "1955", "1956", 1, 1, 1, 2, true))
questions.append(("¿Qué portero fue protagonista en el gol de La Mano de Dios de Maradona?", "A", "Shilton", "Clemence", "Banks", "Woods", 1, 1, 1, 2, true))

# CAT 1 HISTORIA - DIFÍCIL (15)
questions.append(("¿Cuántos goles marcó Gerd Müller solo en el Mundial de 1970?", "B", "9", "10", "8", "11", 1, 1, 1, 3, true))
questions.append(("¿Quién entrenó a Hungría en la final del Mundial de 1954?", "A", "Sebes", "Puskas", "Hidegkuti", "Kocsis", 1, 1, 1, 3, true))
questions.append(("¿En qué año se introdujo la regla del offside moderno?", "C", "1920", "1922", "1925", "1928", 1, 1, 1, 3, true))
questions.append(("¿Cuántos títulos de Copa de Europa ganó el Real Madrid en sus primeras 5 ediciones?", "A", "5", "4", "3", "6", 1, 1, 1, 3, true))
questions.append(("¿Quién marcó el gol del Maracanazo en la final del Mundial de 1950?", "B", "Varela", "Ghiggia", "Schiaffino", "Míguez", 1, 1, 1, 3, true))
questions.append(("¿Cuántos partidos invicto estuvo la selección de Brasil entre 1993 y 1996?", "A", "36", "30", "40", "28", 1, 1, 1, 3, true))
questions.append(("¿Qué partido de Copa de Europa fue el primero en transmitirse por televisión en España?", "D", "Real Madrid vs Juventus", "Barcelona vs Inter", "Athletic vs Chelsea", "Real Madrid vs Milan (1957)", 1, 3))
questions.append(("¿Qué selección ganó la Copa América de 1975 sin jugar como local?", "D", "Brasil", "Argentina", "Perú", "Colombia", 1, 1, 1, 3, true))
questions.append(("¿Quién fue el primer latinoamericano en ganar el Balón de Oro?", "C", "Pelé", "Maradona", "Sivori", "Sánchez", 1, 1, 1, 3, true))
questions.append(("¿Cómo se llamaba el estadio donde se jugó la final del primer Mundial en 1930?", "C", "Estadio Nacional", "La Bombonera", "Estadio Centenario", "Maracaná", 1, 3))
questions.append(("¿Qué árbitro pitó la polémica final del Mundial de 1966?", "A", "Dienst", "Taylor", "Kreitlein", "Horn", 1, 1, 1, 3, true))
questions.append(("¿Cuántos goles marcó Sándor Kocsis en el Mundial de 1954?", "B", "9", "11", "10", "8", 1, 1, 1, 3, true))
questions.append(("¿Qué equipo italiano fue apodado Il Grande Torino?", "A", "Torino FC", "Juventus", "Inter de Milán", "AC Milan", 1, 1, 1, 3, true))
questions.append(("¿En qué año el avión con los jugadores del Grande Torino se estrelló en Superga?", "C", "1947", "1948", "1949", "1950", 1, 1, 1, 3, true))
questions.append(("¿Cuántos Balones de Oro ganó Johan Cruyff?", "B", "2", "3", "4", "1", 1, 1, 1, 3, true))

# CAT 2 INTERNACIONAL - FÁCIL (15)
questions.append(("¿Cuántas Eurocopas ha ganado España?", "C", "2", "1", "4", "3", 2, 1, 1, 1, true))
questions.append(("¿Qué selección ganó el Mundial de 2014?", "A", "Alemania", "Argentina", "Brasil", "Francia", 2, 1, 1, 1, true))
questions.append(("¿Quién ganó la Eurocopa de 2020 (jugada en 2021)?", "B", "Francia", "Italia", "España", "Inglaterra", 2, 1, 1, 1, true))
questions.append(("¿En qué continentes co-organizaron el Mundial de 2002?", "D", "Europa y África", "América y Asia", "Europa y Asia", "Asia (Japón y Corea)", 2, 1, 1, 1, true))
questions.append(("¿Cuántos equipos participan en la fase final de un Mundial desde 1998?", "B", "24", "32", "36", "40", 2, 1, 1, 1, true))
questions.append(("¿Qué jugador fue el máximo goleador del Mundial de 2018?", "C", "Messi", "Ronaldo", "Kane", "Lukaku", 2, 1, 1, 1, true))
questions.append(("¿Quién ganó la Copa América de 2021?", "A", "Argentina", "Brasil", "Uruguay", "Colombia", 2, 1, 1, 1, true))
questions.append(("¿Dónde se celebró el Mundial de 2022?", "B", "Arabia Saudí", "Qatar", "Emiratos Árabes", "Kuwait", 2, 1, 1, 1, true))
questions.append(("¿Qué selección ganó la Eurocopa de 2016?", "C", "Francia", "Gales", "Portugal", "Alemania", 2, 1, 1, 1, true))
questions.append(("¿En qué año ganó España su primer Mundial?", "A", "2010", "2006", "2014", "2002", 2, 1, 1, 1, true))
questions.append(("¿Quién es el máximo goleador histórico de la selección brasileña?", "B", "Pelé", "Neymar", "Ronaldo", "Romário", 2, 1, 1, 1, true))
questions.append(("¿Cuántas Champions League seguidas ganó el Real Madrid entre 2016 y 2018?", "B", "2", "3", "4", "1", 2, 1, 1, 1, true))
questions.append(("¿Quién ganó la Champions League en la temporada 2022-23?", "A", "Manchester City", "Inter de Milán", "Real Madrid", "Bayern Munich", 2, 1, 1, 1, true))
questions.append(("¿Qué selección ganó el Mundial de Brasil 2014 goleando al local 7-1?", "A", "Alemania", "Argentina", "Holanda", "Francia", 2, 1, 1, 1, true))
questions.append(("¿Con qué selección ganó Zinedine Zidane el Mundial?", "B", "Argelia", "Francia", "España", "Italia", 2, 1, 1, 1, true))

# CAT 2 INTERNACIONAL - MEDIA (15)
questions.append(("¿Cuántos goles marcó Miroslav Klose en Mundiales, récord histórico?", "B", "14", "16", "15", "13", 2, 1, 1, 2, true))
questions.append(("¿Qué selecciones comparten el récord de 3 Eurocopas ganadas?", "C", "Francia y Portugal", "Italia y Alemania", "España y Alemania", "España y Portugal", 2, 1, 1, 2, true))
questions.append(("¿Quién fue elegido mejor jugador de la Eurocopa de 2008?", "A", "Xavi", "Iniesta", "Torres", "Villa", 2, 1, 1, 2, true))
questions.append(("¿En qué año ganó Francia su primer Mundial?", "B", "1996", "1998", "2000", "2002", 2, 1, 1, 2, true))
questions.append(("¿Cuántos mundiales disputó Cristiano Ronaldo hasta 2022 inclusive?", "C", "4", "3", "5", "6", 2, 1, 1, 2, true))
questions.append(("¿Qué portero fue clave en la victoria de España en la Eurocopa de 2008?", "A", "Casillas", "De Gea", "Reina", "Valdes", 2, 1, 1, 2, true))
questions.append(("¿Qué selección eliminó a España en el Mundial de Brasil 2014?", "C", "Portugal", "Francia", "Chile", "Holanda", 2, 1, 1, 2, true))
questions.append(("¿Quién marcó el gol de la final de la Eurocopa de 2020 para Italia?", "D", "Immobile", "Insigne", "Barella", "Bonucci", 2, 1, 1, 2, true))
questions.append(("¿Cuántos goles marcó Ronaldo Nazario en Mundiales?", "A", "15", "12", "14", "16", 2, 1, 1, 2, true))
questions.append(("¿Qué selección ganó la Copa Confederaciones de 2017?", "C", "Brasil", "Chile", "Alemania", "Portugal", 2, 1, 1, 2, true))
questions.append(("¿Quién ganó el Balón de Oro del Mundial de 2006?", "B", "Cannavaro", "Zidane", "Ronaldo", "Buffon", 2, 1, 1, 2, true))
questions.append(("¿En qué Mundial fue eliminada Argentina en primera ronda siendo favorita en 2002?", "D", "Francia 1998", "Sudáfrica 2010", "Brasil 2014", "Corea-Japón 2002", 2, 1, 1, 2, true))
questions.append(("¿Quién fue el portero titular de Alemania en el Mundial de 2014?", "A", "Neuer", "Kahn", "Lehmann", "ter Stegen", 2, 1, 1, 2, true))
questions.append(("¿Qué jugador ha marcado goles en 5 Mundiales diferentes?", "C", "Pelé", "Cruyff", "Cristiano Ronaldo", "Messi", 2, 1, 1, 2, true))
questions.append(("¿En qué edición de la Champions League debutó el formato de grupos moderno?", "B", "1990-91", "1992-93", "1994-95", "1996-97", 2, 1, 1, 2, true))

# CAT 2 INTERNACIONAL - DIFÍCIL (15)
questions.append(("¿Qué selección ha marcado más goles en la historia de los Mundiales?", "A", "Alemania/RFA", "Brasil", "Argentina", "Francia", 2, 1, 1, 3, true))
questions.append(("¿En qué edición de la Eurocopa se introdujo el sistema de golden goal?", "B", "Euro 1992", "Euro 1996", "Euro 2000", "Euro 2004", 2, 1, 1, 3, true))
questions.append(("¿Qué falló Roberto Baggio en el Mundial de 1994 que le dio el título a Brasil?", "A", "El penalti de la final", "Un penalti en semis", "Dos penaltis seguidos", "Un gol cantado", 2, 1, 1, 3, true))
questions.append(("¿Cuántos penaltis fallados acumuló la selección inglesa en penaltis de fases finales de torneos entre 1990 y 2020?", "C", "3", "4", "6", "5", 2, 1, 1, 3, true))
questions.append(("¿Qué selección ganó la primera edición de la Copa América en 1916?", "D", "Brasil", "Chile", "Argentina", "Uruguay", 2, 1, 1, 3, true))
questions.append(("¿Cuántos jugadores fueron expulsados en el Partido de la Batalla de Santiago en el Mundial de 1962?", "B", "1", "2", "3", "4", 2, 1, 1, 3, true))
questions.append(("¿Qué sorpresa llegó a semifinales del Mundial de 2002 como anfitrión?", "C", "Senegal", "EE.UU.", "Corea del Sur", "Turquía", 2, 1, 1, 3, true))
questions.append(("¿Cuántos goles en propia puerta hubo en el Mundial de Rusia 2018, récord histórico?", "B", "9", "12", "10", "11", 2, 1, 1, 3, true))
questions.append(("¿Cuál fue el resultado de la mayor goleada de un Mundial?", "A", "Hungría 10-1 El Salvador (1982)", "Brasil 8-1 Suecia", "Alemania 8-0 Arabia Saudí", "Yugoslavia 9-0 Zaire", 2, 1, 1, 3, true))
questions.append(("¿Quién entrenó a Grecia cuando ganó la Eurocopa de 2004?", "A", "Rehhagel", "Skibbe", "Clatis", "Santamaría", 2, 1, 1, 3, true))
questions.append(("¿Cuántos jugadores distintos marcaron gol en la final del Mundial de Francia 1998?", "C", "3", "4", "5", "2", 2, 1, 1, 3, true))
questions.append(("¿Cuántos goles encajó Rusia en la primera fase del Mundial que organizó en 2018?", "D", "3", "4", "2", "7 (en total contra España en los penaltis no, pero en juego...)", 2, 1, 1, 3, true))
questions.append(("¿Qué dato tiene de especial el Madrid al ganar la Champions de 2022 ante el Liverpool?", "B", "Fue la primera vez que ganaron en su campo", "Fue su Champions número 14", "Fue la de Ancelotti más títulos", "Fue sin perder ningún partido", 2, 1, 1, 3, true))
questions.append(("¿Cuántas ediciones de la Eurocopa ganó Alemania Occidental/Alemania hasta 2024?", "A", "3", "4", "2", "5", 2, 1, 1, 3, true))
questions.append(("¿Qué jugador marcó el gol que eliminó a Italia del Mundial de 2002 contra Corea?", "C", "Ahn Jung-hwan para Corea", "Del Piero", "Ahn Jung-hwan (golden goal)", "Totti", 2, 1, 1, 3, true))

# CAT 3 LIGAS - FÁCIL (15)
questions.append(("¿Cuántas veces ha ganado el Real Madrid LaLiga hasta 2024?", "A", "36", "32", "28", "30", 3, 1, 1, 1, true))
questions.append(("¿Qué equipo ha ganado más ligas inglesas?", "B", "Liverpool", "Manchester United", "Chelsea", "Arsenal", 3, 1, 1, 1, true))
questions.append(("¿Quién es el máximo goleador histórico de la Premier League?", "A", "Alan Shearer", "Wayne Rooney", "Andrew Cole", "Thierry Henry", 3, 1, 1, 1, true))
questions.append(("¿Qué club ha ganado más veces la Serie A italiana?", "B", "Inter de Milán", "Juventus", "AC Milan", "Roma", 3, 1, 1, 1, true))
questions.append(("¿En qué año comenzó la Premier League moderna?", "C", "1990", "1991", "1992", "1993", 3, 1, 1, 1, true))
questions.append(("¿Qué equipo ganó la primera Bundesliga en 1963-64?", "A", "Colonia", "Bayern Munich", "Borussia Dortmund", "Eintracht Frankfurt", 3, 1, 1, 1, true))
questions.append(("¿Quién es el máximo goleador histórico de LaLiga española?", "B", "Raúl", "Messi", "Cristiano Ronaldo", "Hugo Sánchez", 3, 1, 1, 1, true))
questions.append(("¿Qué club ganó la Premier League invicto en la temporada 2003-04?", "C", "Chelsea", "Manchester United", "Arsenal", "Liverpool", 3, 1, 1, 1, true))
questions.append(("¿Cuántos equipos juegan en la Bundesliga alemana?", "A", "18", "20", "16", "22", 3, 1, 1, 1, true))
questions.append(("¿Qué jugador ganó 10 ligas españolas con el FC Barcelona?", "B", "Xavi", "Messi", "Puyol", "Iniesta", 3, 1, 1, 1, true))
questions.append(("¿Qué club inglés fue conocido como The Invincibles en 2003-04?", "C", "Chelsea", "Manchester United", "Arsenal", "Liverpool", 3, 1, 1, 1, true))
questions.append(("¿Qué equipo es conocido como Los Blancos?", "B", "Tottenham", "Real Madrid", "Juventus", "Marsella", 3, 1, 1, 1, true))
questions.append(("¿Cuántos equipos disputan la Serie A italiana?", "C", "16", "18", "20", "22", 3, 1, 1, 1, true))
questions.append(("¿Qué ciudad tiene más equipos en la Premier League habitualmente?", "A", "Londres", "Manchester", "Birmingham", "Liverpool", 3, 1, 1, 1, true))
questions.append(("¿Qué equipo ha dominado la Ligue 1 francesa en los últimos 10 años?", "B", "Marsella", "Paris Saint-Germain", "Lyon", "Mónaco", 3, 1, 1, 1, true))

# CAT 3 LIGAS - MEDIA (15)
questions.append(("¿Qué equipo ganó la primera edición de la liga española en 1929?", "A", "FC Barcelona", "Real Madrid", "Athletic Club", "Arenas Club", 3, 1, 1, 2, true))
questions.append(("¿Quién fue el máximo goleador de la Bundesliga en la temporada 2020-21 con 41 goles?", "B", "Haaland", "Lewandowski", "Werner", "Gnabry", 3, 1, 1, 2, true))
questions.append(("¿Cuántas ligas italianas consecutivas ganó la Juventus entre 2012 y 2020?", "C", "7", "8", "9", "10", 3, 1, 1, 2, true))
questions.append(("¿Qué entrenador ganó la liga inglesa con el Chelsea y con el Manchester City?", "A", "Mourinho", "Guardiola", "Wenger", "Ancelotti", 3, 1, 1, 2, true))
questions.append(("¿Qué equipo ganó la Premier League de forma sorprendente en 2015-16?", "D", "Stoke City", "Southampton", "Swansea City", "Leicester City", 3, 1, 1, 2, true))
questions.append(("¿Cuántos goles marcó Cristiano Ronaldo en la temporada récord de LaLiga 2014-15?", "B", "47", "48", "50", "52", 3, 1, 1, 2, true))
questions.append(("¿Qué entrenador llevó al Nottingham Forest a ganar dos Copas de Europa consecutivas?", "A", "Brian Clough", "Ron Atkinson", "Peter Taylor", "Dave Mackay", 3, 1, 1, 2, true))
questions.append(("¿En qué temporada el AC Milán no perdió ningún partido en la Serie A?", "C", "1989-90", "1990-91", "1991-92", "1992-93", 3, 1, 1, 2, true))
questions.append(("¿Cuántos puntos obtuvo el Manchester City en la Premier League 2017-18, récord histórico inglés?", "B", "95", "100", "98", "102", 3, 1, 1, 2, true))
questions.append(("¿En qué temporada el Arsenal ganó la liga inglesa sin perder ningún partido?", "A", "2003-04", "2001-02", "2004-05", "2002-03", 3, 1, 1, 2, true))
questions.append(("¿Qué equipo alemán fue campeón de Bundesliga en la temporada 2023-24 siendo invicto en liga?", "D", "RB Leipzig", "Borussia Dortmund", "Bayern Munich", "Bayer Leverkusen", 3, 1, 1, 2, true))
questions.append(("¿Qué jugador ganó el Pichichi de LaLiga más veces en la historia?", "B", "Cristiano Ronaldo", "Messi", "Zarra", "Hugo Sánchez", 3, 1, 1, 2, true))
questions.append(("¿Cuántos partidos consecutivos sin perder encadenó el Arsenal en la liga entre 2003 y 2004?", "A", "49", "40", "55", "45", 3, 1, 1, 2, true))
questions.append(("¿Qué club ganó la única liga española fuera de Real Madrid y Barcelona entre 2000 y 2020?", "C", "Valencia", "Sevilla", "Atlético de Madrid", "Deportivo de La Coruña", 3, 1, 1, 2, true))
questions.append(("¿Qué entrenador llevó al Liverpool a ganar la Premier League en 2019-20, poniendo fin a 30 años de espera?", "A", "Klopp", "Benitez", "Rodgers", "Dalglish", 3, 1, 1, 2, true))

# CAT 3 LIGAS - DIFÍCIL (15)
questions.append(("¿En qué temporada el Deportivo de La Coruña ganó LaLiga?", "B", "1998-99", "1999-2000", "2000-01", "2001-02", 3, 1, 1, 3, true))
questions.append(("¿Cuántos puntos necesitó el Leicester City para ganar la Premier League en 2015-16?", "A", "81", "79", "85", "77", 3, 1, 1, 3, true))
questions.append(("¿Cuántas temporadas seguidas fue el Olympique de Lyon campeón de la Ligue 1 francesa?", "B", "6", "7", "5", "8", 3, 1, 1, 3, true))
questions.append(("¿Qué entrenador ganó la Bundesliga con el Borussia Dortmund en 2011 y 2012?", "A", "Klopp", "Favre", "Tuchel", "Hitzfeld", 3, 1, 1, 3, true))
questions.append(("¿En qué temporada el Inter de Milán completó el Triplete (liga, copa y Champions)?", "C", "2007-08", "2008-09", "2009-10", "2010-11", 3, 1, 1, 3, true))
questions.append(("¿Qué equipo ganó la liga italiana el año del escándalo Calciopoli de 2005-06 al ser asignada?", "A", "Inter (asignado)", "Milan", "Fiorentina", "Roma", 3, 1, 1, 3, true))
questions.append(("¿Cuántos equipos distintos han ganado la Premier League desde 1992 hasta 2024?", "B", "5", "6", "7", "8", 3, 1, 1, 3, true))
questions.append(("¿En qué año fue campeón de LaLiga el Valencia CF por última vez?", "D", "2000-01", "2001-02", "2003-04", "2003-04", 3, 1, 1, 3, true))
questions.append(("¿Qué récord tiene Thierry Henry en la historia de la Premier League con el Arsenal?", "C", "Máximo goleador en una temporada con 30 goles", "Más asistencias en una temporada", "29 goles en temporada 2003-04", "Primer jugador africano en ganar la liga", 3, 1, 1, 3, true))
questions.append(("¿Qué portero tiene el récord de porterías a cero en una temporada de la Bundesliga?", "B", "Kahn", "Neuer", "Maier", "Lehmann", 3, 1, 1, 3, true))
questions.append(("¿Qué equipo ganó la liga española en la primera temporada sin Messi en el FC Barcelona (2021-22)?", "A", "Atlético de Madrid", "Real Madrid", "Sevilla", "Barcelona", 3, 1, 1, 3, true))
questions.append(("¿En qué año el Athletic Club de Bilbao ganó su última liga española?", "B", "1981", "1984", "1990", "1978", 3, 1, 1, 3, true))
questions.append(("¿Cuántas ligas alemanas ganó el Bayern Munich de forma consecutiva entre 2013 y 2023?", "A", "11", "10", "9", "12", 3, 1, 1, 3, true))
questions.append(("¿Qué jugador fue el máximo goleador de la Bundesliga más veces en la historia?", "B", "Rummenigge", "Gerd Müller", "Lewandowski", "Klose", 3, 1, 1, 3, true))
questions.append(("¿Qué equipo francés ganó la Ligue 1 en 2021-22 rompiendo la hegemonía del PSG?", "D", "Marsella", "Mónaco", "Niza", "Ninguno, la ganó el PSG", 3, 1, 1, 3, true))

print(f"Total preguntas: {len(questions)}")

with open('/home/claude/preguntas_futbol.sql', 'w', encoding='utf-8') as f:
    f.write("-- 135 Preguntas de Fútbol\n")
    f.write("-- Categorías: 1=Historia del Fútbol, 2=Fútbol Internacional, 3=Ligas Nacionales\n")
    f.write("-- Dificultades: 1=Fácil, 2=Media, 3=Difícil\n")
    f.write("-- autor_id=1, validada_por=1, validada=1\n\n")
    f.write("INSERT INTO preguntas (titulo, respuesta_correcta, respuesta_A, respuesta_B, respuesta_C, respuesta_D, categoria_id, autor_id, validada_por, dificultad_id, validada) VALUES\n")
    
    rows = []
    for q in questions:
        titulo, resp, a, b, c, d, cat, dif = q
        def esc(s): return s.replace("'", "\\'")
        row = f"('{esc(titulo)}', '{resp}', '{esc(a)}', '{esc(b)}', '{esc(c)}', '{esc(d)}', {cat}, 1, 1, {dif}, 1)"
        rows.append(row)
    
    f.write(",\n".join(rows))
    f.write(";\n")

print("SQL generado correctamente")
PYEOF
python3 /home/claude/gen.py
Salida

Total preguntas: 135
SQL generado correctamente